### ISSUE TITLE
Ajax in modal

### ISSUE THREAD

**Issue by antiden** [jsimnz/nifty-modal#6]
Thx! Great module. But if load content via ajax, form not centered in window. How can create ajax callback?

**Comment by jsimnz** [comment]
Thanks!

Can you give me a working example that reproduces the problem you are referring to. Either on https://plnkr.co/ or https://jsfiddle.net/

**Comment by antiden** [comment]
Testing here <a href="https://plnkr.co/9YHs4Z8WDNIDzkqSZTuF" target="_blank">plnkr.co</a>

And other bug, if content will be more, no scroll in body. In bootstrap modal i found this code and he work. For class `md-body` adding styles:

`.md-body {
  max-height: calc(100vh - 210px);
  overflow-y: auto;
}`

**Comment by Egeni** [comment]
Hi! Great module. But if I have multiple modal windows on one page and want all blur effect for them? Could you help me?????????? Doesn't work

**Comment by jsimnz** [comment]
Ahhh, ok @antiden. I see what you mean now.

Thanks for brining this to my attention. Haven't used this module with dynamicly loaded content so I hadn't anticipated this as a problem.

I'll look into it.

**Comment by jsimnz** [comment]
@Egeni, could you open a new issue for this. I'd like to keep things seperate. Thanks

**Comment by jsimnz** [comment]
I've added a new `update` command that allows you to reposition the modal after dynamic content has been added to it.

Hope that works for you.

**Comment by antiden** [comment]
It's work pretty good =) You a t best
