### ISSUE TITLE
CSS conflicts

### ISSUE THREAD

**Issue by princeofnaxos** [jsimnz/nifty-modal#8]
There are a few lines in the nifty CSS that conflict with our site's CSS, e.g. the following line:

@media screen and (max-width:32em){body{font-size:75%}}

Clearly, this causes _all_ of our texts to shrink, which is not desirable. Please provide CSS that only touches the modals, such as:

@media screen and (max-width:32em){body **.nifty-modal**{font-size:75%}}

**Comment by jsimnz** [comment]
Yeah, generalized usage wasn't the biggest prority when I first wrote Nifty. This issue was also recently brought up in #7. So I will do a bit of a clean up on the css.

Thanks for bringing this to my attention!

**Comment by empurium** [comment]
Doesn't look like there are too many places, nifty modals seem to isolate their CSS for the most part.
